Fix? CI pipeline (#165)
Fix CI pipeline

Co-authored-by: Henny022 <git@henny022.de>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,23 +16,17 @@ on:
 jobs:
   syntax-check:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Get the CI tool
-        uses: robinraju/release-downloader@v1
+      - uses: actions/checkout@v4
+      - name: log in to ghcr
+        uses: docker/login-action@v3
         with:
-          repository: Ibot02/tmcr-newlogic-ci
-          tag: "v1.0"
-          filename: "tmcr-newlogic-ci"
-          tarBall: false
-          zipBall: false
-
-      - name: Make it executable
-        run: chmod +x "$GITHUB_WORKSPACE/tmcr-newlogic-ci"
-
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Run the CI tool
         run: |
-          cd $GITHUB_WORKSPACE
-          ./tmcr-newlogic-ci tmc/logic/*.logic
+          cd ${{ github.workspace }}
+          mkdir modules
+          mv * modules || echo "ignoring error"
+          docker run -v ./modules:/var/modules ghcr.io/ibot02/tmcr-newlogic-cli /var/modules
